

# This file was *autogenerated* from the file example.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)# Simple graph: C4 w/ single edge tail

# Create C4
G = graphs.CycleGraph(_sage_const_4 )
# Add tail
G.add_vertex(_sage_const_4 )
G.add_edge(_sage_const_3 , _sage_const_4 )

# Labels and (optional) Colours
labels = {_sage_const_0 :'A', _sage_const_1 :'B', _sage_const_2 :'C', _sage_const_3 :'D', _sage_const_4 :'E'}
vertex_colors = ['skyblue','skyblue','skyblue','skyblue','orange']
edge_colors = ['red']

# Show graph
G.plot(vertex_labels=labels, vertex_color=vertex_colors, edge_colors=edge_colors, layout='spring').save('example.png')

